### ISSUE TITLE
itemValues.txt does not generate and game crashes on world reload

### ISSUE THREAD

**Issue by salamoonderrepos** [skycatminepokie/wbshop#18]
The folder which contains the custom item values does not generate. The changelog says it should be located here:
<ProfileName>/config/wbshop/itemValues.txt

![image](https://github.com/skycatminepokie/wbshop/assets/57581728/9ad14a41-1399-4f93-89d6-a0872ffe56ba)
(It should be right under the folder titled "voicechat")

When I create a new world, leave, and rejoin the world, it crashes. However, if I load my game again it loads just fine until I leave the world and load it again which is when it crashes.
I'm quite sure it only crashes once you leave the world and then load it again.
![image](https://github.com/skycatminepokie/wbshop/assets/57581728/9362b0a9-23e6-41c5-81b4-d5cb01e7cfeb)

I tested both issues without other mods and just using plain fabric and still got the same problems.
![image](https://github.com/skycatminepokie/wbshop/assets/57581728/01ece0f2-b34a-42d1-87f2-5c0dad4e7dbf)
(Config folder)

Also for some reason the border was reset back to it's original place after the crash but this might have just been the world reverting back to an old automatic backup it made.

My friends and I really enjoy using this mod and having custom point values for items is a feature we've been wanting since we found the mod in the first place. Keep up the cool stuff you're making! 

P.S. If this isn't the right place for this post please direct me to the correct place.

**Comment by skycatminepokie** [comment]
Perfect place to report this, thank you! I'll take a look today.

**Comment by skycatminepokie** [comment]
Fixed this, thank you for letting me know :D
